export enum BOOK_ACTION_TYPES {
  SET_BOOK = "books/SET_BOOK",
  FETCH_BOOK_START = "books/FETCH_BOOK_START",
  FETCH_BOOK_SUCCESS = "books/FETCH_BOOK_SUCCESS",
  FETCH_BOOK_FAILED = "books/FETCH_BOOK_FAILED",
}

export type BookActionType =
  | typeof BOOK_ACTION_TYPES.SET_BOOK
  | typeof BOOK_ACTION_TYPES.FETCH_BOOK_START
  | typeof BOOK_ACTION_TYPES.FETCH_BOOK_SUCCESS
  | typeof BOOK_ACTION_TYPES.FETCH_BOOK_FAILED;
