export enum WISHLIST_ACTION_TYPES {
  WISHLIST_START = "wishlist/WISHLIST_START",
  WISHLIST_FAILED = "wishlist/WISHLIST_FAILED",
  FETCH_WISHLIST_SUCCESS = "wishlist/FETCH_WISHLIST_SUCCESS",
  ADD_WISHLIST_SUCCESS = "wishlist/ADD_WISHLIST_SUCCESS",
  DELETE_WISHLIST_SUCCESS = "wishlist/DELETE_WISHLIST_SUCCESS",
}

export type WishlistActionType =
  | typeof WISHLIST_ACTION_TYPES.WISHLIST_START
  | typeof WISHLIST_ACTION_TYPES.WISHLIST_FAILED
  | typeof WISHLIST_ACTION_TYPES.FETCH_WISHLIST_SUCCESS
  | typeof WISHLIST_ACTION_TYPES.ADD_WISHLIST_SUCCESS
  | typeof WISHLIST_ACTION_TYPES.DELETE_WISHLIST_SUCCESS;
